[package]
name = "crates"
version = "0.1.0"
edition = "2021"

[dependencies]
console = "0.15.0"
tokio = { version = "1.18.2", features = ["full"] }
surf = "2.3.2"
serde = "1.0.37"
serde_json = "1.0.81"